name: CI on push

on:
    push: 
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Running script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh